services:
  user-service:
    build: ./user-service
    ports:
      - "4000:4000"
    networks:
      - memo-net
    environment:
      - MONGO_URI=mongodb://mongo:27017/user-service
      - JWT_SECRET=your_jwt_secret

  memo-service:
    build: ./memo-service
    ports:
      - "3000:3000"
    networks:
      - memo-net
    environment:
      - MONGO_URI=mongodb://mongo:27017/memo-service

  search-service:
    build: ./search-service
    ports:
      - "5000:5000"
    networks:
      - memo-net
    environment:
      - MONGO_URI=mongodb://mongo:27017/memo-service

  frontend:
    build: ./frontend
    ports:
      - "80:3000"
    networks:
      - memo-net

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - memo-net
    volumes:
      - mongo-data:/data/db

networks:
  memo-net:
    driver: bridge

volumes:
  mongo-data:
